### ISSUE TITLE
Download and deletion through web ui does not work

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/schematic.cloud#77]
**Observed behavior**

1. Navigate to https://schematic.cloud/download/ or /delete/
2. Enter the download key `6bc922311d3cd0556b99d456e787da2e`, generated ingame via `/plot download`
3. Page loads and time-outs.

**Expected behavior**
I am able to download or delete my schematic.
![Screenshot 2023-01-02 at 11 37 55](https://user-images.githubusercontent.com/13383509/210220442-ef3463e0-b05b-4b6f-b522-e0122ce4eb5e.png)

**Comment by PierreSchwang** [comment]
Fixed with 43cb7983067faaefe4f4871dc776c4a3eb0b0cc8 - Tested with following docker-compose:

```yaml
version: '3.8'

services:
  schematic-web:
    container_name: Schematic-Web
    networks:
      web:
    image: intellectualsites/schematic-web:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.schem-web.entrypoints=websecure"
      - "traefik.http.routers.schem-web.rule=Host(`schematic-web.pschwang.eu`)"
      - "traefik.http.routers.schem-web.tls=true"
      - "traefik.http.routers.schem-web.service=schem-web"
      - "traefik.http.services.schem-web.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
```
